# Generated by Django 5.0.1 on 2024-01-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=40)),
                ('instructions', models.TextField()),
                ('allowed_languages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=40)),
                ('tags', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('constraints', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('solution', models.TextField()),
                ('hints', models.TextField()),
                ('creator', models.CharField(max_length=40)),
                ('time_limit', models.DurationField()),
                ('memory_limit', models.CharField(max_length=40)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Contest.contest')),
            ],
        ),
    ]
